/**
 * @created_at: 2019-06-29 23:10:03
 * @author: Aaron Delasy
 * @license_start
 *
 * Copyright (c) 2018-2019  Aaron Delasy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @license_end
 */

#ifndef SRC_CODEGEN_MAC64HEADER_H
#define SRC_CODEGEN_MAC64HEADER_H

#include "../Binary.h"

#define CODEGEN_MAC_64_HEADER_MAGIC 0xFEEDFACF
#define CODEGEN_MAC_64_HEADER_CIGAM 0xCFFAEDFE

#define CODEGEN_MAC_64_HEADER_CPU_ARCH_MASK 0xFF000000u
#define CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64 0x01000000u
#define CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64_32 0x02000000u

#define CODEGEN_MAC_64_HEADER_CPU_TYPE_ANY -1
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_UNKNOWN 0u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_VAX 1u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_MC680X0 6u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_X86 7u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_I386 CODEGEN_MAC_64_HEADER_CPU_TYPE_X86
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_X86_64 \
  (CODEGEN_MAC_64_HEADER_CPU_TYPE_X86 | CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64)
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_MC98000 10u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_HPPA 11u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_ARM 12u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_ARM64 \
  (CODEGEN_MAC_64_HEADER_CPU_TYPE_ARM | CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64)
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_ARM64_32 \
  (CODEGEN_MAC_64_HEADER_CPU_TYPE_ARM | \
    CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64_32)
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_MC88000 13u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_SPARC 14u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_I860 15u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_POWERPC 18u
#define CODEGEN_MAC_64_HEADER_CPU_TYPE_POWERPC64 \
  (CODEGEN_MAC_64_HEADER_CPU_TYPE_POWERPC | \
    CODEGEN_MAC_64_HEADER_CPU_ARCH_ABI64)

#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MASK 0xFF000000u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_LIB64 0x80000000u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MULTIPLE -1
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_LITTLE_ENDIAN 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_BIG_ENDIAN 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX780 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX785 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX750 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX730 4u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_UVAXI 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_UVAXII 6u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX8200 7u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX8500 8u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX8600 9u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX8650 10u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_VAX8800 11u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_UVAXIII 12u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC680X0_ALL 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC68030 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC68040 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC68030_ONLY 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_I386_ALL 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_386 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_486 4u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_486SX 132u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_586 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENT 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTPRO 22u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTII_M3 54u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTII_M5 86u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_CELERON 103u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_CELERON_MOBILE 119u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_3 8u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_3_M 24u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_3_XEON 40u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_M 9u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_4 10u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_PENTIUM_4_M 26u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ITANIUM 11u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ITANIUM_2 27u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_XEON 12u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_XEON_MP 28u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_X86_ALL 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_X86_64_ALL 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_X86_ARCH1 4u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_X86_64_H 8u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R2300 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R2600 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R2800 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R2000_A 4u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R2000 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R3000_A 6u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MIPS_R3000 7u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC98000_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC98601 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_HPPA_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_HPPA_7100 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_HPPA_7100LC 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC88000_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC88100 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MC88110 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_SPARC_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_I860_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_I860_860 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_601 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_602 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_603 3u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_603_E 4u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_603_EV 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_604 6u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_604_E 7u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_620 8u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_750 9u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_7400 10u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_7450 11u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_POWERPC_970 100u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V4T 5u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V6 6u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V5TEJ 7u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_XSCALE 8u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7 9u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7F 10u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7S 11u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7K 12u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V6M 14u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7M 15u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V7EM 16u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM_V8 13u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM64_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM64_V8 1u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM64E 2u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM64_32_ALL 0u
#define CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_ARM64_32_V8 1u

#define CODEGEN_MAC_64_HEADER_FILE_TYPE_UNKNOWN 0x0u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_OBJECT 0x1u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_EXECUTE 0x2u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_FVMLIB 0x3u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_CORE 0x4u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_PRELOAD 0x5u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_DYLIB 0x6u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_DYLINKER 0x7u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_BUNDLE 0x8u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_DYLIB_STUB 0x9u
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_DSYM 0xAu
#define CODEGEN_MAC_64_HEADER_FILE_TYPE_KEXT_BUNDLE 0xBu

#define CODEGEN_MAC_64_HEADER_FLAG_UNKNOWN 0x0u
#define CODEGEN_MAC_64_HEADER_FLAG_NOUNDEFS 0x1u
#define CODEGEN_MAC_64_HEADER_FLAG_INCRLINK 0x2u
#define CODEGEN_MAC_64_HEADER_FLAG_DYLDLINK 0x4u
#define CODEGEN_MAC_64_HEADER_FLAG_BINDATLOAD 0x8u
#define CODEGEN_MAC_64_HEADER_FLAG_PREBOUND 0x10u
#define CODEGEN_MAC_64_HEADER_FLAG_SPLIT_SEGS 0x20u
#define CODEGEN_MAC_64_HEADER_FLAG_LAZY_INIT 0x40u
#define CODEGEN_MAC_64_HEADER_FLAG_TWOLEVEL 0x80u
#define CODEGEN_MAC_64_HEADER_FLAG_FORCE_FLAT 0x100u
#define CODEGEN_MAC_64_HEADER_FLAG_NOMULTIDEFS 0x200u
#define CODEGEN_MAC_64_HEADER_FLAG_NOFIXPREBINDING 0x400u
#define CODEGEN_MAC_64_HEADER_FLAG_PREBINDABLE 0x800u
#define CODEGEN_MAC_64_HEADER_FLAG_ALLMODSBOUND 0x1000u
#define CODEGEN_MAC_64_HEADER_FLAG_SUBSECTIONS_VIA_SYMBOLS 0x2000u
#define CODEGEN_MAC_64_HEADER_FLAG_CANONICAL 0x4000u
#define CODEGEN_MAC_64_HEADER_FLAG_WEAK_DEFINES 0x8000u
#define CODEGEN_MAC_64_HEADER_FLAG_BINDS_TO_WEAK 0x10000u
#define CODEGEN_MAC_64_HEADER_FLAG_ALLOW_STACK_EXECUTION 0x20000u
#define CODEGEN_MAC_64_HEADER_FLAG_ROOT_SAFE 0x40000u
#define CODEGEN_MAC_64_HEADER_FLAG_SETUID_SAFE 0x80000u
#define CODEGEN_MAC_64_HEADER_FLAG_NO_REEXPORTED_DYLIBS 0x100000u
#define CODEGEN_MAC_64_HEADER_FLAG_PIE 0x200000u
#define CODEGEN_MAC_64_HEADER_FLAG_DEAD_STRIPPABLE_DYLIB 0x400000u
#define CODEGEN_MAC_64_HEADER_FLAG_HAS_TLV_DESCRIPTORS 0x800000u
#define CODEGEN_MAC_64_HEADER_FLAG_NO_HEAP_EXECUTION 0x1000000u
#define CODEGEN_MAC_64_HEADER_FLAG_APP_EXTENSION_SAFE 0x02000000u
#define CODEGEN_MAC_64_HEADER_FLAG_NLIST_OUTOFSYNC_WITH_DYLDINFO 0x04000000u
#define CODEGEN_MAC_64_HEADER_FLAG_SIM_SUPPORT 0x08000000u

namespace let {
  class CodegenMac64Header {
   public:
    int32 cpuType = CODEGEN_MAC_64_HEADER_CPU_TYPE_UNKNOWN;
    int32 cpuSubType = CODEGEN_MAC_64_HEADER_CPU_SUBTYPE_MULTIPLE;
    uint32 fileType = CODEGEN_MAC_64_HEADER_FILE_TYPE_UNKNOWN;
    uint32 cmdsCount = 0;
    uint32 cmdsSize = 0;
    uint32 flags = CODEGEN_MAC_64_HEADER_FLAG_UNKNOWN;
    uint32 reserved = 0;

    uint32 getSize();
    Binary toBinary();

   private:
    uint32 magic = CODEGEN_MAC_64_HEADER_MAGIC;
  };
}

#endif
