/**
 * @created_at: 2019-06-30 14:30:49
 * @author: Aaron Delasy
 * @license_start
 *
 * Copyright (c) 2018-2019  Aaron Delasy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @license_end
 */

#ifndef SRC_CODEGEN_MAC64SECTION_H
#define SRC_CODEGEN_MAC64SECTION_H

#include "../Binary.h"

#define CODEGEN_MAC64_COMMANDSEGMENT_DATA "__DATA"
#define CODEGEN_MAC64_COMMANDSEGMENT_ICON "__ICON"
#define CODEGEN_MAC64_COMMANDSEGMENT_IMPORT "__IMPORT"
#define CODEGEN_MAC64_COMMANDSEGMENT_LINKEDIT "__LINKEDIT"
#define CODEGEN_MAC64_COMMANDSEGMENT_OBJC "__OBJC"
#define CODEGEN_MAC64_COMMANDSEGMENT_PAGEZERO "__PAGEZERO"
#define CODEGEN_MAC64_COMMANDSEGMENT_TEXT "__TEXT"
#define CODEGEN_MAC64_COMMANDSEGMENT_UNIXSTACK "__UNIXSTACK"

#define CODEGEN_MAC64_SECTION_BSS "__bss"
#define CODEGEN_MAC64_SECTION_COMMON "__common"
#define CODEGEN_MAC64_SECTION_DATA "__data"
#define CODEGEN_MAC64_SECTION_FVMLIB_INIT0 "__fvmlib_init0"
#define CODEGEN_MAC64_SECTION_FVMLIB_INIT1 "__fvmlib_init1"
#define CODEGEN_MAC64_SECTION_ICON_HEADER "__header"
#define CODEGEN_MAC64_SECTION_ICON_TIFF "__tiff"
#define CODEGEN_MAC64_SECTION_OBJC_MODULES "__module_info"
#define CODEGEN_MAC64_SECTION_OBJC_REFS "__selector_refs"
#define CODEGEN_MAC64_SECTION_OBJC_STRINGS "__selector_strs"
#define CODEGEN_MAC64_SECTION_OBJC_SYMBOLS "__symbol_table"
#define CODEGEN_MAC64_SECTION_TEXT "__text"

#define CODEGEN_MAC64_SECTION_FLAG_ATTR_USR 0xFF000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_PURE_INSTRUCTIONS 0x80000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_NO_TOC 0x40000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_STRIP_STATIC_SYMS 0x20000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_NO_DEAD_STRIP 0x10000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_LIVE_SUPPORT 0x08000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_SELF_MODIFYING_CODE 0x04000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_DEBUG 0x02000000u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_SYS 0x00FFFF00u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_SOME_INSTRUCTIONS 0x00000400u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_EXT_RELOC 0x00000200u
#define CODEGEN_MAC64_SECTION_FLAG_ATTR_LOC_RELOC 0x00000100u

#define CODEGEN_MAC64_SECTION_FLAG_REGULAR 0x0u
#define CODEGEN_MAC64_SECTION_FLAG_ZEROFILL 0x1u
#define CODEGEN_MAC64_SECTION_FLAG_CSTRING_LITERALS 0x2u
#define CODEGEN_MAC64_SECTION_FLAG_4BYTE_LITERALS 0x3u
#define CODEGEN_MAC64_SECTION_FLAG_8BYTE_LITERALS 0x4u
#define CODEGEN_MAC64_SECTION_FLAG_LITERAL_POINTERS 0x5u
#define CODEGEN_MAC64_SECTION_FLAG_NON_LAZY_SYMBOL_POINTERS 0x6u
#define CODEGEN_MAC64_SECTION_FLAG_LAZY_SYMBOL_POINTERS 0x7u
#define CODEGEN_MAC64_SECTION_FLAG_SYMBOL_STUBS 0x8u
#define CODEGEN_MAC64_SECTION_FLAG_MOD_INIT_FUNC_POINTERS 0x9u
#define CODEGEN_MAC64_SECTION_FLAG_MOD_TERM_FUNC_POINTERS 0xAu
#define CODEGEN_MAC64_SECTION_FLAG_COALESCED 0xBu
#define CODEGEN_MAC64_SECTION_FLAG_GB_ZEROFILL 0xCu
#define CODEGEN_MAC64_SECTION_FLAG_INTERPOSING 0xDu
#define CODEGEN_MAC64_SECTION_FLAG_16BYTE_LITERALS 0xEu
#define CODEGEN_MAC64_SECTION_FLAG_DTRACE_DOF 0xFu
#define CODEGEN_MAC64_SECTION_FLAG_LAZY_DYLIB_SYMBOL_POINTERS 0x10u
#define CODEGEN_MAC64_SECTION_FLAG_THREAD_LOCAL_REGULAR 0x11u
#define CODEGEN_MAC64_SECTION_FLAG_THREAD_LOCAL_ZEROFILL 0x12u
#define CODEGEN_MAC64_SECTION_FLAG_THREAD_LOCAL_VARIABLES 0x13u
#define CODEGEN_MAC64_SECTION_FLAG_THREAD_LOCAL_VARIABLE_POINTERS 0x14u
#define CODEGEN_MAC64_SECTION_FLAG_THREAD_LOCAL_INIT_FUNCTION_POINTERS 0x15u
#define CODEGEN_MAC64_SECTION_FLAG_INIT_FUNC_OFFSETS 0x16u

namespace let {
  class CodegenMac64Section {
   public:
    uint64 address = 0;
    uint64 size = 0;
    uint32 offset = 0;
    uint32 align = 0;
    uint32 reallocOffset = 0;
    uint32 reallocCount = 0;
    uint32 flags = CODEGEN_MAC64_SECTION_FLAG_REGULAR;
    uint32 reserved1 = 0;
    uint32 reserved2 = 0;
    uint32 reserved3 = 0;

    explicit CodegenMac64Section(const String &, const String &);

    uint32 getSize();
    Binary toBinary();

   private:
    String secName;
    uint32 secNameSize = 16;
    String segName;
    uint32 segNameSize = 16;
  };
}

#endif
